services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: translations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - '5050:80'
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data: